---
loopback_base: "192.168.1"
evpn_route_target_asn: 65000

links:
  - leaf: clab-aristaceos-leaf01
    spine: clab-aristaceos-spine01
    leaf_intf: Ethernet1
    spine_intf: Ethernet1
    leaf_ip: 10.0.0.0/31
    spine_ip: 10.0.0.1/31

  - leaf: clab-aristaceos-leaf01
    spine: clab-aristaceos-spine02
    leaf_intf: Ethernet2
    spine_intf: Ethernet1
    leaf_ip: 10.0.0.2/31
    spine_ip: 10.0.0.3/31

  - leaf: clab-aristaceos-leaf02
    spine: clab-aristaceos-spine01
    leaf_intf: Ethernet1
    spine_intf: Ethernet2
    leaf_ip: 10.0.0.4/31
    spine_ip: 10.0.0.5/31

  - leaf: clab-aristaceos-leaf02
    spine: clab-aristaceos-spine02
    leaf_intf: Ethernet2
    spine_intf: Ethernet2
    leaf_ip: 10.0.0.6/31
    spine_ip: 10.0.0.7/31

  - leaf: clab-aristaceos-leaf03
    spine: clab-aristaceos-spine01
    leaf_intf: Ethernet1
    spine_intf: Ethernet3
    leaf_ip: 10.0.0.8/31
    spine_ip: 10.0.0.9/31

  - leaf: clab-aristaceos-leaf03
    spine: clab-aristaceos-spine02
    leaf_intf: Ethernet2
    spine_intf: Ethernet3
    leaf_ip: 10.0.0.10/31
    spine_ip: 10.0.0.11/31

  - leaf: clab-aristaceos-leaf04
    spine: clab-aristaceos-spine01
    leaf_intf: Ethernet1
    spine_intf: Ethernet4
    leaf_ip: 10.0.0.12/31
    spine_ip: 10.0.0.13/31

  - leaf: clab-aristaceos-leaf04
    spine: clab-aristaceos-spine02
    leaf_intf: Ethernet2
    spine_intf: Ethernet4
    leaf_ip: 10.0.0.14/31
    spine_ip: 10.0.0.15/31

vlans:
  - { id: 10, vni: 10010, gateway: 10.10.10.1/24, vrf: TENANT-10, l3_vni: 90010 }
  - { id: 20, vni: 10020, gateway: 10.10.20.1/24, vrf: TENANT-20, l3_vni: 90020 }
